spring:
  application:
    name: schim
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/schim}
    username: ${SPRING_DATASOURCE_USERNAME:schim}
    password: ${SPRING_DATASOURCE_PASSWORD:schim}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB